In [2]:
import numpy as np

# Numpy Matrix Operations

In [3]:
np.dot(np.array([[1,-1],[0,1]]),np.array([[1,-1],[0,1]])) # OK

array([[ 1, -2],
       [ 0,  1]])

In [4]:
np.array([[1,-1],[0,1]]).dot( np.array([[1,-1],[0,1]]) )

array([[ 1, -2],
       [ 0,  1]])

In [104]:
# Test dazu
A = np.array([[1,2,3],
              [0,5,6],
              [0,0,9]])
print(A)
A=np.roll(A,(-1,-1),axis=(0,1))
print(A)
A[-1,:] = 0
print(A)
A[:,-1] = [10,11,12]
print(A)

[[1 2 3]
 [0 5 6]
 [0 0 9]]
[[5 6 0]
 [0 9 0]
 [2 3 1]]
[[5 6 0]
 [0 9 0]
 [0 0 0]]
[[ 5  6 10]
 [ 0  9 11]
 [ 0  0 12]]


In [139]:
A = np.arange(2*3).reshape(2,3)
B = np.arange(2*3).reshape(3,2).T
print("A: {}".format(A))
print("B: {}".format(B))

print(np.diag(np.einsum("ik,ik -> k",A,B))) # This is only the diagonal of AT B
print(np.einsum("ik,ij",A,B)) # This is AT B 

A: [[0 1 2]
 [3 4 5]]
B: [[0 2 4]
 [1 3 5]]
[[ 3  0  0]
 [ 0 14  0]
 [ 0  0 33]]
[[ 3  4  5]
 [ 9 14 19]
 [15 24 33]]
